name: 'Docker Build & Push'
on:
    push:
        branches: ['main']
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-jvm

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'zulu'
                  cache: maven
            - name: Package
              run: ./mvnw --no-transfer-progress clean package
            - name: Docker Login
              uses: docker/login-action
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker Metadata
              id: metadata
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Docker Build and Push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: './src/main/docker/Dockerfile.jvm'
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
